#!/usr/bin/env python3
# File Name:
# multiPDFReadData.py
# Author Information:
# Andrew Sullivan
# amsullivan2@wpi.edu
# June 30, 2021
# Decription:
# This program takes a .CSV generated by OpenBCI's Cyton board,
# processes the data to remove extraneous data points, graphs the data points,
# and then saves the graphs as PDFs. This version saves the PDFs for the 16
# channels seperately. singlePDFReadData.py saves them as one PDF.
# License:
# Software License Agreement (BSD License)
# Find the full agreement at https://github.com/ajcorey/NREIP-SUMMER-2021/blob/main/LICENSE


# Import the libraries that we need
import os
import pandas as pd
from datetime import datetime

## The next line is for if you are getting a message in the terminal
## about matplotlib and its cache, comment out the next line if needed
os.environ['MPLCONFIGDIR'] = os.getcwd() + "/configs/"
import matplotlib.pyplot as plt


# Ask the user for the file name
print('Please ensure that the dataset file is in the Datasets/ directory')
fileNameInput = input('Please Input the file name WITHOUT the file extension: ')


# Set up the filepaths and for later
filePath = os.path.dirname(os.path.abspath(__file__))
os.makedirs(filePath + '/Outputs/' + str(fileNameInput) + '/', exist_ok = True)
inputFilePath = filePath + '/Datasets/'
filePath = os.path.dirname(os.path.abspath(__file__)) + '/Outputs/' + str(fileNameInput) + '/'


# Set variable for the filename to make changing easier later on
bciFileName = str(fileNameInput)
outputCSVFileName = filePath + bciFileName + 'Output.csv'
pdfFileName = filePath + bciFileName


# Convert the file from .TXT to .CSV if needed
continueFlag = True
while continueFlag:
    print('Does this file need to be converted from .TXT to .CSV?')
    needsConversion = input('Y/N: ')
    needsConversion = str(needsConversion.upper())
    if needsConversion == 'Y' or needsConversion == 'YES':
        csvFileName = inputFilePath + bciFileName + '.txt'
        tempName = inputFilePath + bciFileName + '.csv'
        os.rename(csvFileName, tempName)
        csvFileName = inputFilePath + bciFileName + '.csv'
        print('File converted successfully!')
        continueFlag = False

    elif needsConversion == 'N' or needsConversion == 'NO':
        csvFileName = inputFilePath + bciFileName + '.csv'
        print('File will not be converted!')
        continueFlag = False

    else:
        print('Invalid option, please try again!')
        print()


# Try loop that allows for a graceful exit if needed
try:
    # Make the DataFrame, read the .CSV, and skip the header and information rows
    df = pd.read_csv(csvFileName, skiprows = 5, header = None)


    # Delete unnecessary columns and rename the remaining ones
    df = df.drop(df.index[17:32], axis = 1)
    df = df.drop(df.columns[[0]], axis = 1)
    df.columns = ['Channel01', 'Channel02', 'Channel03', 'Channel04', 'Channel05', 'Channel06', 'Channel07', 'Channel08', 'Channel09', 'Channel10', 'Channel11', 'Channel12', 'Channel13', 'Channel14', 'Channel15', 'Channel16', 'Timestamp']


    # Convert the formatted timestamp to UNIX
    print('Converting Timestamps!')
    for i in range(0, len(df)):
        formattedDate = df.iloc[i, 16]
        unixDate = datetime.strptime(formattedDate, ' %Y-%m-%d %H:%M:%S.%f').strftime("%s.%f")[:-3]
        df.iat[i, 16] = unixDate


    # Clean the data with a Simple Moving Average (SMA) with a window of 100
    print('Cleaning Data!')
    df['SMA_100_01'] = df.iloc[:,0].rolling(window=100).mean()
    df['SMA_100_02'] = df.iloc[:,1].rolling(window=100).mean()
    df['SMA_100_03'] = df.iloc[:,2].rolling(window=100).mean()
    df['SMA_100_04'] = df.iloc[:,3].rolling(window=100).mean()
    df['SMA_100_05'] = df.iloc[:,4].rolling(window=100).mean()
    df['SMA_100_06'] = df.iloc[:,5].rolling(window=100).mean()
    df['SMA_100_07'] = df.iloc[:,6].rolling(window=100).mean()
    df['SMA_100_08'] = df.iloc[:,7].rolling(window=100).mean()
    df['SMA_100_09'] = df.iloc[:,8].rolling(window=100).mean()
    df['SMA_100_10'] = df.iloc[:,9].rolling(window=100).mean()
    df['SMA_100_11'] = df.iloc[:,10].rolling(window=100).mean()
    df['SMA_100_12'] = df.iloc[:,11].rolling(window=100).mean()
    df['SMA_100_13'] = df.iloc[:,12].rolling(window=100).mean()
    df['SMA_100_14'] = df.iloc[:,13].rolling(window=100).mean()
    df['SMA_100_15'] = df.iloc[:,14].rolling(window=100).mean()
    df['SMA_100_16'] = df.iloc[:,15].rolling(window=100).mean()


    # Convert DataFrame to a .CSV
    df.to_csv(outputCSVFileName, index = False)
    print('Output .CSV Saved!')


    # plot the data
    print('Now Plotting Data!')

    ## Sets up variables for plotting
    x = df.Timestamp
    y01 = df.SMA_100_01
    y02 = df.SMA_100_02
    y03 = df.SMA_100_03
    y04 = df.SMA_100_04
    y05 = df.SMA_100_05
    y06 = df.SMA_100_06
    y07 = df.SMA_100_07
    y08 = df.SMA_100_08
    y09 = df.SMA_100_09
    y10 = df.SMA_100_10
    y11 = df.SMA_100_11
    y12 = df.SMA_100_12
    y13 = df.SMA_100_13
    y14 = df.SMA_100_14
    y15 = df.SMA_100_15
    y16 = df.SMA_100_16


    # Plot the data, save the data as a PDF, clear the plot, and
    # start again and run one channel at a time.

    ## Channel 1 Plot and Save
    plt.title('Channel 01 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y01, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_01.pdf'), dpi = 2400)
    print('Channel 01 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 2 Plot and Save
    plt.title('Channel 02 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y02, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_02.pdf'), dpi = 2400)
    print('Channel 02 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 3 Plot and Save
    plt.title('Channel 03 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y03, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_03.pdf'), dpi = 2400)
    print('Channel 03 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 4 Plot and Save
    plt.title('Channel 04 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y04, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_04.pdf'), dpi = 2400)
    print('Channel 04 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 5 Plot and Save
    plt.title('Channel 05 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y05, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_05.pdf'), dpi = 2400)
    print('Channel 05 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 6 Plot and Save
    plt.title('Channel 06 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y06, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_06.pdf'), dpi = 2400)
    print('Channel 06 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 7 Plot and Save
    plt.title('Channel 07 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y07, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_07.pdf'), dpi = 2400)
    print('Channel 07 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 8 Plot and Save
    plt.title('Channel 08 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y08, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_08.pdf'), dpi = 2400)
    print('Channel 08 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 9 Plot and Save
    plt.title('Channel 09 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y09, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_09.pdf'), dpi = 2400)
    print('Channel 09 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 10 Plot and Save
    plt.title('Channel 10 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y10, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_10.pdf'), dpi = 2400)
    print('Channel 10 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 11 Plot and Save
    plt.title('Channel 11 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y11, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_11.pdf'), dpi = 2400)
    print('Channel 11 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 12 Plot and Save
    plt.title('Channel 12 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y12, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_12.pdf'), dpi = 2400)
    print('Channel 12 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 13 Plot and Save
    plt.title('Channel 13 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y13, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_13.pdf'), dpi = 2400)
    print('Channel 13 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 14 Plot and Save
    plt.title('Channel 14 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y14, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_14.pdf'), dpi = 2400)
    print('Channel 14 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 15 Plot and Save
    plt.title('Channel 15 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y15, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_15.pdf'), dpi = 2400)
    print('Channel 15 Data Plot Saved as PDF!')
    plt.clf()

    ## Channel 16 Plot and Save
    plt.title('Channel 16 Data')
    frame1 = plt.gca()
    frame1.axes.get_xaxis().set_visible(False)
    plt.plot(x, y16, linewidth = 0.5, color = '#FF1B8D')
    plt.savefig((pdfFileName + '_Channel_16.pdf'), dpi = 2400)
    print('Channel 16 Data Plot Saved as PDF!')
    print('All Channels Successfully Plotted and Saved as PDFs!')
    plt.clf()

    ## Commented out to save time, feel free to uncomment for interactive plot
    # plt.show()


# Graceful exit
except (KeyboardInterrupt, SystemExit):
    print ("Exiting.")
    exit
